const quizTypes = {
    
    FETCH_QUIZES_START : 'FETCH_QUIZES_START',
    FETCH_QUIZES_SUCCESS : 'FETCH_QUIZES_SUCCESS',
    FETCH_QUIZES_ERROR : 'FETCH_QUIZES_ERROR',

    FETCH_SINGLEQUIZ_START : 'FETCH_SINGLEQUIZ_START',
    FETCH_SINGLEQUIZ_SUCCESS : 'FETCH_SINGLEQUIZ_SUCCESS',
    FETCH_SINGLEQUIZ_ERROR : 'FETCH_SINGLEQUIZ_ERROR',

    CREATE_QUIZ_START : 'CREATE_QUIZ_START',
    CREATE_QUIZ_SUCCESS : 'CREATE_QUIZ_SUCCESS',
    CREATE_QUIZ_ERROR : 'CREATE_QUIZ_ERROR',

    

}

export default quizTypes;