# Generated by Django 2.2.1 on 2019-07-26 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('short_name', models.CharField(blank=True, max_length=50)),
                ('logo_url', models.URLField(blank=True, max_length=400)),
                ('short_bio', models.TextField()),
                ('starting_year', models.IntegerField()),
                ('no_of_students', models.IntegerField()),
                ('no_of_teachers', models.IntegerField()),
                ('contact_number', models.DecimalField(decimal_places=0, max_digits=10)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=354)),
                ('facebook', models.URLField(max_length=400)),
                ('twitter', models.URLField(max_length=400)),
                ('instagram', models.URLField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='NormalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='HeroImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('caption', models.CharField(max_length=150)),
                ('image_url', models.URLField(blank=True, max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=150)),
                ('image_url', models.URLField(max_length=400)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=354)),
                ('subject', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Website.Brand')),
            ],
        ),
    ]
