# Generated by Django 2.2.1 on 2019-07-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='facebook',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='brand',
            name='instagram',
            field=models.URLField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='brand',
            name='twitter',
            field=models.URLField(blank=True, max_length=400),
        ),
    ]
