# Generated by Django 2.2.1 on 2019-07-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Website', '0004_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='address',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
