# Generated by Django 2.2.1 on 2019-06-04 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0002_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='students',
            new_name='student',
        ),
        migrations.AddField(
            model_name='report',
            name='gained_marks',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
