# Generated by Django 2.2.1 on 2019-07-26 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0004_auto_20190604_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ('-pub_date',), 'verbose_name_plural': 'Quizzes'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ('-submission_date',)},
        ),
    ]
