# Generated by Django 2.2.1 on 2019-12-01 17:32

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Quiz', '0005_auto_20190726_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='option_text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=tinymce.models.HTMLField(),
        ),
    ]
